unique_ids:
  assets:
    standard-page.html: ISG2NUIXPCCLDS23STDDRITU7BYY5QNL
    theme.css: 677RMVRGIYL35XBMTPUCZ4BN35PXQMXE
    u5914788576_httpss.mj.runKeclNKnKozg_A_stylized_candlestick_s_b18b0082-b701-4a00-b5d5-54e76fa53027_1.png: '1757382488196709221110694.7268'
  forms:
    Form1: XBPYLBTVSLDIRUG65BJIJAZ2HHJSISQQ
  modules: {}
  scripts: {}
  server_modules: {}
